### ISSUE TITLE
Fix readme installation instructions

### ISSUE THREAD

**Issue by DenDos** [venuv/langchain_yt_tools#1]
readme says we should run 
`pip -r install requirements.txt`

but it should be `pip install -r requirements.txt`

**Comment by YoussefMadkour** [comment]
Pytube error [pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple](https://stackoverflow.com/questions/68945080/pytube-exceptions-regexmatcherror-get-throttling-function-name-could-not-find)

**Comment by venuv** [comment]
fixed readme
