### ISSUE TITLE
Pytube error 

### ISSUE THREAD

**Issue by YoussefMadkour** [venuv/langchain_yt_tools#2]
[pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple](https://stackoverflow.com/questions/68945080/pytube-exceptions-regexmatcherror-get-throttling-function-name-could-not-find)

there is an error with the latest pytube version, imported yt-dlp as youtube_dl and used it to download instead of pytube, because the latest pytube and youtube_dl have errors with yt downloads

**Comment by venuv** [comment]
see if the code works for you with pytube 12.1.3. if so i'll freeze it at that while I try to migrate to a more modern version
